### ISSUE TITLE
addRecipe in mutations is returning an erro when adding an item.

### ISSUE THREAD

**Issue by saeid78** [ratracegrad/meal-prep#2]
Hello,
Thanks for this nice tutorial! However there is an error on the add item when orderRecipe method gets clicked! it throws an error like "[vuex] unknown action type: addRecipe"
I could not figure it out.
Thanks.

**Comment by ratracegrad** [comment]
Send me a link to your code and I will look into it. It is looking for an
action in the store called addRecipe and it is not there. Either you have
not added or spelled it slightly differently.

Jennifer Bland

sent from my rotary phone

**Comment by saeid78** [comment]
Hi again,
I sorted out the action in the store.js file and it's working now!
Thanks.
