### ISSUE TITLE
issue in mobile

### ISSUE THREAD

**Issue by yashpalchhajer** [ratracegrad/meal-prep#3]
I am trying to open this in mobile but it's menus are not working on mobile.

**Comment by ratracegrad** [comment]
Yes, I forgot to circle back and update the navigation in the drawer after updating it in the toolbar. Will get it updated.

**Comment by Jerry-Merchand** [comment]
Hey Jennifer, did you ever get this navigation drawer working? I'm reading your 4 part article and it well written! I have just reviewed your code in github and reviewed the code in the article and i can't get the nav drawer working either. I'm just pulling out your code and building a mobile app for the phones for work. I don't need any firebase code. Also you have some data-cr code pointing to what appears is button click handlers in your templates but no code.

TIA! Jerry

**Comment by Jerry-Merchand** [comment]
In order to fix the drawer for item click, I had to add the following code:
<v-list-tile :key="index" :to="item.route">
The solution for me was to add :to="item.route" to the <v-list-tile> begin tag. It took me some looking around the web, but, it was worth the hunt!

**Comment by ratracegrad** [comment]
I have updated the code to add a link for items in the menu in the navigation side drawer. Pull and you will have it working on mobile.
