### ISSUE TITLE
Exposed API-Key in /src/firebase/index.js

### ISSUE THREAD

**Issue by felixfrtz** [ratracegrad/meal-prep#4]
Check that `/src/firebase/index.js` doesn't contain your real API-Key.

**Comment by wr125** [comment]
Please refer to the image below
![vue](https://user-images.githubusercontent.com/20228047/92934202-20491980-f43f-11ea-99d1-3863e14fc76d.png)

In my ./src/firebase/index.js i have the following set;
apiKey: "api-key",
  authDomain: "app.firebaseapp.com",
  databaseURL: "https://app.firebaseio.com",
  projectId: "app",
  storageBucket: "app.appspot.com",
  messagingSenderId: "0.0.0.0",
  appId: "app_id"

Note: not signed up to gcloud with credit card yet
