### ISSUE TITLE
After log in [vuex] do not mutate vuex store state outside mutation handlers.

### ISSUE THREAD

**Issue by victorsolaya** [ratracegrad/meal-prep#5]
Hi, 

When I try to log in I have the following error 
[vuex] do not mutate vuex store state outside mutation handlers.
It is because the commits inside the login function:

`userLogin({ commit }, { email, password }) {
            firebase
                .auth()
                .signInWithEmailAndPassword(email, password)
                .then(user => {
                    commit('setUser', user);
                    commit('setIsAuthenticated', true);
                    this.$router.push('/');
                })
                .catch(() => {
                    commit('setUser', null);
                    commit('setIsAuthenticated', false);
                    this.$router.push('/login');
                });
        },`
 
If I commit these two:

commit('setUser', user);
commit('setIsAuthenticated', true);
the function works without any problem.

**Comment by bentomlin** [comment]
Yes, this should be a dispatchable action which then mutates. One doesn't mutate directly
